### ISSUE TITLE
Germline sequence above the predicted sequence in the Alignment pile-up

### ISSUE THREAD

**Issue by avilella** [snijderlab/stitch#160]
Hi,

In the same way that the report shows the germline and predicted proteins aligned to each other at the beginning of the report, it would be useful to show the Germline sequence above the predicted sequence further down in the Alignment pile-up, possibly colouring the peptides according to them mismatching the germline.

In this way, if there are lots of peptides mismatching the germline in a region, one would be confident that the difference against the germline is real, but if there is a combination of matches and mismatches in the different peptides in another region, one would be less confident of that difference.

I hope it makes sense

**Comment by douweschulte** [comment]
Closing the issue because the discussion has stalled and the proposal was not clear enough to drive implementation. If the discussion springs back to life the issue can be openend again.
