### ISSUE TITLE
Research W ion usage

### ISSUE THREAD

**Issue by douweschulte** [snijderlab/stitch#193]
Find out how W ions are annotated in Hecklib. Find some examples of the ion in the 'wild' (or generated datasets). This could prove useful for #81.

**Comment by douweschulte** [comment]
The used fragmentation model at this time does not search for W ions. Use the following snippets to build it in:
```C#
new AnnotatedSpectrumMatch(asm.Spectrum, asm.Match, new PeptideFragment.FragmentModel(asm.Model){ Y = null, Z = null })
```
_And example code from the modelAll_
```C#
W = new PeptideFragment.FragmentRange { MinPos = 0, MaxPos = PeptideFragment.SEQUENCELENGTH - 1, HigherCharges = true, MassShifts = PeptideFragment.MASSSHIFT_NEUTRALLOSS | PeptideFragment.MASSSHIFT_WATERLOSS | PeptideFragment.MASSSHIFT_AMMONIALOSS | PeptideFragment.MASSSHIFT_HYDROGENGAIN | PeptideFragment.MASSSHIFT_CAPITALGAIN | PeptideFragment.MASSSHIFT_HYDROGENLOSS | PeptideFragment.MASSSHIFT_CAPITALLOSS | PeptideFragment.MASSSHIFT_MODIFICATIONLOSS },
```

Currently used model: https://bms-developer.science.uu.nl/csharp/hecklib-core/-/blob/master/Source/HeckLib/chemistry/PeptideFragment.cs#L659

**Comment by douweschulte** [comment]
After discussion with Richard it is clear that adding the definition for `Y` for `W` would be perfectly fine. That would result in the following code:
```c#
new AnnotatedSpectrumMatch(asm.Spectrum, asm.Match, new PeptideFragment.FragmentModel(asm.Model){ 
    W = new PeptideFragment.FragmentRange { 
        MinPos = 1, 
        MaxPos = PeptideFragment.SEQUENCELENGTH - 1, 
        HigherCharges = true, 
        MassShifts = PeptideFragment.MASSSHIFT_WATERLOSS | PeptideFragment.MASSSHIFT_AMMONIALOSS }})
```

**Comment by douweschulte** [comment]
Some issues with this were fixed and the d ions were also included to provide more confidence.

**Comment by Ln9052** [comment]
Hi Schulte, 
I'd like to confirm whether the "RawDataDirectory" parameter in Stitch for identifying I/L has been deprecated. If "RawDataDirectory" has indeed been deprecated, are there alternative methods available for I/L identification? 
Thank you.

**Comment by douweschulte** [comment]
No it has not, it has moved to be specified on each file separately. This was done to allow for opening multiple dataset with unrelated raw file locations. Please not that for the I/L disambiguation you will have to specify this as an additional parameter for each file as well. `XleDisambiguation: True`.

So here is a small example of how this would look:
```
Input ->
    Peaks -->
        Path: Some path
        RawDataDirectory: /the/path/
        XleDisambiguation: True
        - any further settings
    <-
<-
```

**Comment by Ln9052** [comment]
Hi Schulte, When attempting to use Stitch parameters "XleDisambiguation" and "RawDataDirectory", I encountered IO issues during execution. There seems to be a problem with opening and reading the file. Could you please provide suggestions on resolving this issue? Thank you.
Input ->
    pNovo ->
        Path     :Path...\...\result\results.res
        Param  :Path...\...\param\pNovo.param
        Name     :1
        CutoffScore   :90
       RawDataDirectory:F:\lining_data\MAHH_raw\1ul\HCl_4min.raw
       XleDisambiguation  :True 
 ![image](https://github.com/snijderlab/stitch/assets/152148969/2ca3360c-64d4-4725-82e2-28436bfb72e3)

**Comment by douweschulte** [comment]
As the parameter name implies `RawDataDirectory` assumes the path to be a directory. So you will have to change your batchfile line from `RawDataDirectory:F:\lining_data\MAHH_raw\1ul\HCl_4min.raw` into `RawDataDirectory:F:\lining_data\MAHH_raw\`. I will make a better error message for this case as I have seen other people getting stuck on the same error.

**Comment by Ln9052** [comment]
I tried using the latest nightly version of Stitch#374https://github.com/snijderlab/stitch/actions/runs/7006838956，When I modified the line in my batch file from 'RawDataDirectory:F:\lining_data\MAHH_raw\1ul\HCl_4min.raw' to either 'RawDataDirectory:F:\lining_data\MAHH_raw' or 'RawDataDirectory:F:\lining_data\MAHH_raw\1ul', I encountered an error during execution. Could you please take a look at this issue for me? Thank you.
![image](https://github.com/snijderlab/stitch/assets/152148969/de858bdc-bb8e-496a-bfe4-8f5f53b2a00b)
![image](https://github.com/snijderlab/stitch/assets/152148969/aaaccc28-82b4-4831-bb13-a9038080ea7b)
Error: Could not open file
   │ F:\lining_data\MAHH_raw\1ul\
note: The file given is a directory.
help: Make sure you are trying to open the correct raw data for this dataset.

**Comment by douweschulte** [comment]
The problem is that the output of pNovo makes it really hard to find the correct raw file. You seem to have run pNovo on a mgf file with a different format then I expected. For now I updated the code so that it should skip any raw data it did not find instead of giving this error. But this does not make the spectra work in your case. If you want the spectra to work you can send me the pNovo files so I can build in support for the slightly different format it has in your case.

**Comment by douweschulte** [comment]
I fixed the parsing to take this format as well. With the new nightly this should work from now on.

**Comment by Ln9052** [comment]
Hi Schulte, I've noticed three things. Firstly, in the Maxnovo section of the manual, there's a parameter called Fixedmodification, and it's generally considered that M+16 is a variable modification. I'm curious about your perspective on the use of adding M+16 in the Fixedmodification parameter. 
<img width="400" alt="image" src="https://github.com/snijderlab/stitch/assets/152148969/32d5f047-877d-4e08-9b12-74abc5750b5e">
Additionally, when using Stitch to read Maxnovo results, I receive a warning: 'Warning: Could not parse pro forma sequence │ CTAEETDIINNM[Oxidation (M)]YPR note: The program will continue, but the spectra will be missing for this peptide (MN:15469).' It seems that the appearance of M[Oxidation (M)] in the Maxnovo results sequence might interfere with parsing. Could you take a look at my batchfiles
[monoclonal_maxnovo.txt](https://github.com/snijderlab/stitch/files/13495607/monoclonal_maxnovo.txt)
 and [msmsScans.txt](https://github.com/snijderlab/stitch/files/13495614/msmsScans.txt) to help identify the reason? 
Furthermore, I've noticed that the RawDataDirectory parameter is not listed in the manual for Stitch when reading Novor files. Can you clarify whether Stitch can disambiguate I/L when reading Novor files?
<img width="398" alt="image" src="https://github.com/snijderlab/stitch/assets/152148969/e98007ee-cebd-4355-a910-0380e9d9c09e">

**Comment by douweschulte** [comment]
Regarding the fixed modification, it is indeed weird to have oxidation as fixed modification. Although it should be quite harmless to put it here as an example I think it more clear to remove it.

The parsing error you see is because I use [ProForma](https://github.com/HUPO-PSI/ProForma) for the definition of peptide sequences and the [unimod definition](https://unimod.org/modifications_view.php?editid1=35) for oxidation used in that format is written `M[Oxidation]`. These errors happen because it seems like every file format has devised their own names for modifications. As you see in the error though the failure to parse the sequence will only prevent this one peptide from having its spectrum shown, otherwise no ill effect is to be had. If this behaviour is unacceptable or you find many more of these modifications that break I could look into adding a list of known sloppy names to resolve in the parser.

For the Novor data, there is a parameter `RawFile` where you can give the path to the raw file used for this Novor run. The `XleDisambiguation` parameter is also working. I updated the manual. Thanks for raising the question!
