### ISSUE TITLE
Building in Windows cmd

### ISSUE THREAD

**Issue by kostrouc** [snijderlab/stitch#203]
Hi,

I am not able to get any of the building scripts to run in the command prompt on windows x64. I ran the previous ".\stitch.exe batchfiles\monoclonal.txt" and it generated a report (despite not having a raw input file). Please see errors below and advise.

```
Directory of C:\Users\kostrouchov\Downloads

11/04/2022  11:38 AM    <DIR>          .
11/04/2022  11:38 AM    <DIR>          ..
10/21/2022  10:29 AM    <DIR>          alphabets
10/21/2022  10:29 AM    <DIR>          assets
10/21/2022  10:29 AM    <DIR>          batchfiles
10/21/2022  10:29 AM    <DIR>          datasets
11/04/2022  11:38 AM       206,765,072 dotnet-sdk-6.0.402-win-x64.exe
10/21/2022  10:29 AM    <DIR>          images
10/21/2022  10:29 AM             1,105 License.md
10/21/2022  10:29 AM             4,308 README.md
11/04/2022  01:14 PM    <DIR>          results
11/04/2022  10:14 AM        98,339,213 stitch-v1.3.0-windows.zip
10/21/2022  10:29 AM        91,327,396 stitch.exe
10/21/2022  10:29 AM        91,927,336 stitch_arm.exe
10/21/2022  10:29 AM    <DIR>          templates
               6 File(s)    488,364,430 bytes
               9 Dir(s)  123,844,067,328 bytes free

C:\Users\kostrouchov\Downloads>dotnet run --project stitch batchfiles\monoclonal.txt
MSBUILD : error MSB1009: Project file does not exist.
Switch: stitch

The build failed. Fix the build errors and run again.

C:\Users\kostrouchov\Downloads>dotnet publish stitch -c release --self-contained
MSBuild version 17.3.2+561848881 for .NET
MSBUILD : error MSB1009: Project file does not exist.
Switch: stitch

C:\Users\kostrouchov\Downloads>mklink /J stitch\bin\debug\net6.0\assets\ assets\
The system cannot find the path specified.

C:\Users\kostrouchov\Downloads>mklink /J stitch\bin\debug\net6.0\images\ images\
The system cannot find the path specified.
```

**Comment by douweschulte** [comment]
These commands you show are for building the program from source (the c# source code) while you downloaded the built binaries. If you want to build the program from source, which you need if you want to change the code in some way, you need for clone the repository with git.
You need to clone the repo with this url `https://github.com/snijderlab/stitch.git` (which you can also find on the home page on the green button). You can clone it using `git clone <url>` or refer to a guide like this one: https://www.atlassian.com/git/tutorials/setting-up-a-repository/git-clone.

I hoped that cleared it up.

**Comment by douweschulte** [comment]
And as a side note, stitch does not need any raw data to function. For now it only uses the raw data to show the spectra in the HTML pages. It only needs a list of de Novo sequenced peptide from software like Peaks, if there is another software package you are using do share an example file so I can update stitch to be able to use files from that software as well.
