### ISSUE TITLE
Specifying Non-local Output Dir

### ISSUE THREAD

**Issue by kostrouc** [snijderlab/stitch#204]
Hi,

I noticed that the building requires stitch be installed on a local directory using ```mklink```. Is there any way to specify an output directory with ```dotnet run --project stitch```? I didn't see anything listed under ```--help```.

**Comment by kostrouc** [comment]
Ah I believe this is specified in the batch file that is provided.

From batchfiles\basic.txt:
```
Report ->
    HTML ->
        Path    : ../results/{datetime} {name}/report-basic.html
    <-
<-
``

**Comment by douweschulte** [comment]
It is indeed specified there. If you take a look at the manual that is also bundled with the program you will be able to find the full definition of what you can do with this setting. [You can find this here.](https://github.com/snijderlab/stitch/blob/master/BatchFiles.md#report) Keep in mind that all paths in the whole batchfile are seen relative to the location of the batchfile itself.
