### ISSUE TITLE
Reformatting Datasets CSV

### ISSUE THREAD

**Issue by kostrouc** [snijderlab/stitch#205]
Hi,

I have a custom de novo sequencing algorithm which generated some resulting predicted peptide sequences. May you tell me which input columns I am missing that may be required for stitch to function properly with a polyclonal antibody dataset from rabbit?

I have attached the example csv input file along with the edited polyclonal batchfile.

Below is the error I recieve when I run the script in command prompt:
```
Y:\Katie\stitch>.\stitch.exe batchfiles\RabbitPolyclonal.txt
>                                                                                                          |   0%  35 ms
>> Error: Object reference not set to an instance of an object.
 --> Stacktrace:
| Stitch.InputNameSpace.ParseHelper.ParseTemplateMatching(NameFilter nameFilter, KeyValue key)
| Stitch.ParseCommandFile.Batch(String path)
| Stitch.ToRunWithCommandLine.RunBatchFile(String filename, RunVariables runVariables)
| Stitch.ToRunWithCommandLine.Main()
Version: 1.3.0+b7279d1
```
[rabbit_test.csv](https://github.com/snijderlab/stitch/files/9983042/rabbit_test.csv)
[RabbitPolyclonal.txt](https://github.com/snijderlab/stitch/files/9983048/RabbitPolyclonal.txt)

**Comment by douweschulte** [comment]
I added the examples of the file formats to the documentation as promised above, the link from the previous message is still valid. Besides that I found the cause of the crash you reported below is the error message you would get with the nightly version of stitch (the version that I am currently working on).

```
There was 1 error while parsing.

Error: Could not open file
   ╭── ~\RabbitPolyclonal.txt:32:30
   │
30 │         Heavy Chain->
31 │             Segment->
32 │                 Path      : ../templates/Oryctolagus_cunicus_IGHV.fasta
   ·                             ──────────────────────────────────────────────────────────────────
33 │                 Name      : IGHV
34 │                 Identifier: ^(([a-zA-Z]+\d*)[\w-]*)
   ╵
note: The specified file could not be found.
help: Did you mean 'Oryctolagus_cuniculus_IGHC_uniprot.fasta'?
```

**Comment by kostrouc** [comment]
Is the ALC (%) column required for the recombination step? 

I noticed that just using a text file with only peptide sequences on each new line generates a template matching and recombination result. See attached format of input reads and batch file.

[r1.txt](https://github.com/snijderlab/stitch/files/9984080/r1.txt)
[rabbit_reads.txt](https://github.com/snijderlab/stitch/files/9984081/rabbit_reads.txt)

**Comment by douweschulte** [comment]
No the ALC column is not necessary, any of the input file formats will work fine. The only reason for all the other files to exist is so that it is easier for users to use the software while maintaining all of the meta data the de novo peptide sequencing software generated.

**Comment by kostrouc** [comment]
Thank you! This was very helpful!

**Comment by douweschulte** [comment]
You are welcome
