### ISSUE TITLE
Support MaxQuant database search input data

### ISSUE THREAD

**Issue by douweschulte** [snijderlab/stitch#238]
Allowing users to read in MaxQuant database searches would allow some nice analyses we normally do on de novo data to be done on database data with a bit more certainty of the data correctness.
[msms.txt](https://github.com/snijderlab/stitch/files/12451869/msms.txt)
WP

**Comment by Ln9052** [comment]
Hi,

Recently, I have encountered an issue when using Stitch to read the msmsScan.txt file generated by Maxnovo. The error reported is "Line has too low amount of fields (70)." Additionally, I attempted to use Stitch to read the [msms.txt](https://github.com/snijderlab/stitch/files/13470927/msms.txt) file provided in your last comments , but encountered the same error. In my understanding, this error indicates that there is a low number of fields during the data parsing process starting from the second line. Have you also observed this issue? Furthermore, do you have any suggestions or methods for resolving this issue?

Thank you!
<img width="322" alt="图片1" src="https://github.com/snijderlab/stitch/assets/152148969/46841d97-4939-4f1e-b572-e3f88b90db1a">

**Comment by douweschulte** [comment]
Currently there is no support for any `msms.txt` file generated by Maxquant either in de novo or database matching function. The `msmsScans.txt` file generated after de novo analysis is the only file supported, so in that case if the file does not work please send it to me so I can see what the problem is.

**Comment by douweschulte** [comment]
MaxNovo seems to have changed their format a little bit. I fixed up the code in stitch that reads in these files to allow for this newer format. See the most recent nightly build to have this fix applied.

**Comment by Ln9052** [comment]
Thank you very much, following your instructions, Stitch successfully read the Maxnovo file.
