### ISSUE TITLE
How could I use stitch to analyze my antibody sequence produced by PEAKS ?

### ISSUE THREAD

**Issue by huyoyo2001** [snijderlab/stitch#239]
I run the the code **.\stitch.exe batchfiles\monoclonal.txt** ,before that I put my file in dataset, named my file as the input of file name mentioned by monoclonal, and I maintained format and  headers just same as your original csv file. But it reported errors like **not a valid number**.

**Comment by douweschulte** [comment]
It could be that you use a different version of Peaks compared to what we normally use, what version did you use? Can you show an excerpt of the peaks file you want to run using Stitch? Just the top 10 lines for example, the full file is also fine if you, but if you do not want that to be public just send it to my email `d.schulte<AT>uu.nl`.

**Comment by huyoyo2001** [comment]
Thanks for your reply! Firstly, I used PEAKS AB, and the exported file is like this 
![截屏2023-09-13 下午6 13 48](https://github.com/snijderlab/stitch/assets/144894090/190350b1-13a1-4612-8096-553382068b6b)
after that I found my format and content of my file is different from yours so I edit my file like this 
![IMG_2554](https://github.com/snijderlab/stitch/assets/144894090/3aaa10c7-09f6-42fa-9299-3a04252c020a)
finally, I downloaded PEAKS Studio 11, but the exported file is also different and only contain sequence of one certain enzyme, like this
![IMG_2555](https://github.com/snijderlab/stitch/assets/144894090/e242c899-dd02-4b38-a6d9-47a55d664092)
I tried all these files on the basis that I could run your original files successfully.

**Comment by douweschulte** [comment]
That explains why it did not work, I have never had Peaks 11 files before, we are still using 10 here. For the edited data you showed in the second picture you are missing the 'Predict RT' column after 'RT' column L, this column can be filled with cells that are all '-' as is the case for the example dataset. If for the other two formats you showed all columns I can get you an update to stitch shortly that can handle these formats. But for that it would be really helpful the have the full files so I can test them on my side.

**Comment by huyoyo2001** [comment]
Thank you so much! I'll send my data to you!

**Comment by douweschulte** [comment]
I just pushed an update that supports peaks Ab. To use type 'Ab' in place of the 'X+' for the format field of the peaks data in your batchfile. Note that it normally takes about an hour before all tests are run and the new nightly version can be downloaded.

If you also have some peaks 11 data you want to run feel free to send me an example dataset, then I will build support for that as well. Otherwise I will add support when we get our hands on our own install of peaks 11 in a couple of weeks.

Thanks for opening the issue, I am always happy to support more input formats to make it possible to run Stitch for everyone. And feel free to reach out again if this does not work for you.

**Comment by huyoyo2001** [comment]
Hi I downloaded the new version, and tried again on the base of that I could run your original data successfully, but it still report errors like this, maybe I used the wrong way to run my own data? So could you please describe the detailed steps about how could I use the software to analyze my own data? By the way, I use the Windows system.
![image](https://github.com/snijderlab/stitch/assets/144894090/3a9f1672-e677-4774-9bf3-1a16c105e4c2)

**Comment by huyoyo2001** [comment]
Ok thank you so much, I have run it successfully, I did not change the batchfile to Ab last time.

**Comment by pikiton** [comment]
[](url)Hi, I have used the files from Peaks 10 and everything works fine, but there is a problem when processing a file from PeaksAB.

Also I didn't understand if it is possible to use files from peaks 11? And where can I download the latest "nightly" [versions?](![Screenshot 2023-11-10 234839](https://github.com/snijderlab/stitch/assets/120220014/f352ff51-544a-4ef6-9f02-95ef83ef3cb5))

**Comment by douweschulte** [comment]
You seem to have used an older version of Stitch from before I build in the support for peaks 11 and peaks Ab. The nightly version you can find here: https://github.com/snijderlab/stitch/actions. Then go to the last run, click it, scroll down, and there you can find the `nightly-deploy-{system}` zips files.

**Comment by douweschulte** [comment]
Setting `Format: 11` is the way to go, but make sure you use a very recent version of Stitch as the support for Peaks 11 was only added very recently. Use a nightly version or `v1.5.0-rc.1` (which you can find in the releases tab).

**Comment by MengTingHe2023** [comment]
Thank you so much, I have run it successfully,
