### ISSUE TITLE
Unrecognized Casanovo result.mztab file line start code

### ISSUE THREAD

**Issue by Ln9052** [snijderlab/stitch#242]
Hi Schulte, currently, I've encountered an issue when using Stitch to read "result.mztab" file from Casanovo. The error message reads, for example, 
![image](https://github.com/snijderlab/stitch/assets/152148969/3f532bc2-019d-4002-836c-5112802ad074)
However, I have verified the beginning lines of the "result.mztab" file and ensured that they start with valid codes. 
![image](https://github.com/snijderlab/stitch/assets/152148969/effa02b7-7122-454c-aef2-dd7acb324ef3)
What steps should I take to resolve this issue?Do you have any helpful suggestions? 
Thank you.

**Comment by douweschulte** [comment]
That is indeed looking quite weird. Could you send me the full file? Either as attachment here in the issue or to my email (d.schulte(AT)uu.nl)? That way I will be able to check what is wrong on my side.

**Comment by Ln9052** [comment]
Thank you for your response. Could you please take a look at file "sample_preprocessed_spectra.mztab" and try to read the file according to the manual of Stitch， to identify the cause of the issue mentioned above? Thank you once more for your assistance. 


-----原始邮件-----
发件人:"Douwe Schulte" ***@***.***>
发送时间:2023-11-27 18:45:42 (星期一)
收件人: snijderlab/stitch ***@***.***>
抄送: Ln9052 ***@***.***>, Author ***@***.***>
主题: Re: [snijderlab/stitch] Unrecognized Casanovo result.mztab file line start code (Issue #242)






That is indeed looking quite weird. Could you send me the full file? Either as attachment here in the issue or to my email (d.schulte(AT)uu.nl)? That way I will be able to check what is wrong on my side.

**Comment by douweschulte** [comment]
I am afraid attaching files in this way does not work could you try sending it to me directly or adding it to this issue via the webinterface of github?

**Comment by Ln9052** [comment]
![image](https://github.com/snijderlab/stitch/assets/152148969/698690a0-c5bf-44a8-a1a7-51245ec74e65)

**Comment by douweschulte** [comment]
It seems to support gzipped files (.zip/.gz) so you could try to zip it first.

**Comment by douweschulte** [comment]
Thanks I will take a look at it!

**Comment by douweschulte** [comment]
I did not get the same error. But the file contained many empty lines, for which I found a way to generate this output which I hope to have built a fix for. I additionally found that this file contains charge with a decimal point (`2.0` instead of `2`) which would give an error as well. Both are fixed and the nightly build based on the commit I just made has these fixes applied. If this new version does not work for you let me know and I will take another look. 
_Note:_ the automated build pipeline takes about 1 hour for all benchmarking to finish, only after that time will the nightly binaries be available.

**Comment by Ln9052** [comment]
Thank you very much. I will carefully review your comments and make adjustments based on the actual experience of running the nightly version of Stitch. Thanks again.

**Comment by Ln9052** [comment]
Hi Schulte, I found that this nightly version #372[ Small mztab issues for #242 #372](https://github.com/snijderlab/stitch/actions/runs/7006476567) did not work for me. This is my batchfile. 
[monoclonal_try_casanovo.txt](https://github.com/snijderlab/stitch/files/13483403/monoclonal_try_casanovo.txt)
And this is the error information. Thanks.
![image](https://github.com/snijderlab/stitch/assets/152148969/ce125188-df1f-4087-bb7a-a3f1573efc18)

**Comment by douweschulte** [comment]
The trouble is that the file has a lot of weird newlines ('enters') and these break while reading them in. My test computer runs linux , and there it works, but this stuff works differently on windows. I will try to make a fix in the code itself, but you could also, if you feel comfortable, change the file to not contain these newlines. For this open the file in a text editor, copy the empty line you see there and replace this (control+H in most programs) with nothing. That should make the file run immediately without having to wait for my fix.

**Comment by douweschulte** [comment]
With some further inspection I see that your file uses `\r\r\n` as newline pattern, which is extremely weird. What kind of system did you run Casanovo on? This pattern does not work well with the code I wrote to always detect the newline pattern for any file, as this is not a sensible newline pattern. I attached the file where I replaced `\r\r\n` with `\r\n` which is the normal newline pattern on windows. This file should work. If there are any more problems feel free to let me know.
[sample_preprocessed_spectra_normalised.zip](https://github.com/snijderlab/stitch/files/13486452/sample_preprocessed_spectra_normalised.zip)

**Comment by Ln9052** [comment]
Thank you very much. I am running casanovo on a Windows system, and its result file contains many empty lines. I will attempt to use the file you sent to see if stitch can read it, compare the differences between the two files, and try to identify the reasons for their differences.

**Comment by douweschulte** [comment]
If you are running Casanovo from windows that could be the reason why it is so weird, then maybe an issue should be raised in Casanovo itself, so they can fix their output.

**Comment by Ln9052** [comment]
I have just used the file you provided, and it ran successfully. Thank you for your advice and suggestions. The issue may lie in Casanovo's output.Thank you very much for your assistance.

**Comment by wenjinwu1985** [comment]
HELP  "I used the code provided below, but after running it, I encountered the following error. What could be the cause of this issue?  
User
Error: Not a valid number
      ╭── D:\stitch-v1.5.0-windows\DETA TEST\hawk.mztab:19809:227
      │
19807 │ PSM SYTLLELPPTPSGTTTLSKGNVVT 19746 null null null null "[MS, MS:1003281, Casanovo, 4.1.0]" -0.505144049 null nu …
19808 │ PSM LSADLDELM+15.995DTALREELQNPLEELREEVGTHLDLS 19747 null null null null "[MS, MS:1003281, Casanovo, 4.1.0]" -0 …
19809 │ …=19767 null null null null "0.27434,0.24810,0.24681,0.20568,0.23882,0.23139,0.20678,0.24179,0.22357,0.19806,0.…
      ·                                                             ────────
19810 
[Uploading hawk.zip…]()

**Comment by wenjinwu1985** [comment]
-Run Info---------------
Version         : 1.5
Runname         : monoclonal_try_HT-280

- Here the input can be defined, this will be used in the TemplateMatching and Recombine steps
Input ->
    Casanovo ->
        Path     : D:\stitch-v1.5.0-windows\DETA TEST\hawk2.mztab
        Name     : try_casanovo
        FilterPPM: 10
        CutoffScore: 0.9
        FragmentationMethod: All
    <-
<-

- Template matching matches the reads defined in 'Input' to the given Templates defined in the different groups in the 'Segments'
TemplateMatching ->
    EnforceUnique      : 0.9
    CutoffScore        : 10
    AmbiguityThreshold : 0.9

    include!(../alphabets/mass_alphabet.txt)

    Segments->
        include!(../templates/Homo_sapiens_Heavy_Chain.txt)
        include!(../templates/Homo_sapiens_Light_Chain.txt)
        include!(../templates/common_contaminants.txt)
    <-
<-

Recombine->
    -Pick the <n> highest scoring templates from each segment
    N          : 1
    -Decoy      : True
    CutoffScore: 10

    -Separated by whitespace means directly attached
    -Separated by * means with a gap attached
    Order->
        Homo sapiens Heavy Chain: IGHV * IGHJ IGHC
        Homo sapiens Light Chain: IGLV IGLJ IGLC
    <-
<-

Report ->
    Folder: ../results/{datetime} {name}/
    HTML ->
        Path: report-monoclonal.html
    <-
    FASTA ->
        Path: report-monoclonal-tm.fasta
        OutputType: TemplateMatching
    <-
    CSV ->
        Path: report-monoclonal-tm.csv
        OutputType: TemplateMatching
    <-
    FASTA ->
        Path: report-monoclonal-rec.fasta
        OutputType: Recombine
    <-
    CSV ->
        Path: report-monoclonal-rec.csv
        OutputType: Recombine
    <-
<-
