### ISSUE TITLE
How can I use Stitch to assemble my peptide sequences?

### ISSUE THREAD

**Issue by huangli1219** [snijderlab/stitch#245]
Hello Sir,
 I used PEAKS to generated my peptides sequences and exported them into csv. format. I would like to ask if I use Stitch to assemble them, can I just edit the **path**and **Format** in **monoclonal.txt** from **batchfiles**, then run the **monoclonal.txt** ? Do I need to modify other places?

**Comment by douweschulte** [comment]
Yes, that's it! Unless you want Stitch to behave differently in some areas that is all you need. So, I would advise to just try it out, looks through the results and see what it does. Once you have a bit of an understanding of how it works you can play with the settings to make the runs more specific for your usecase. If you want more information about specific settings, or an overview of which exist, take a look at the manual that you can find next to the download. 
As I assume this answers your question I will close this issue, if you have any other questions feel free to ask!
