### ISSUE TITLE
Error in Casanovo file parsing

### ISSUE THREAD

**Issue by wenjinwu1985** [snijderlab/stitch#248]
HELP "[Uploading hawk.zip…]()
```
Error: Not a valid number
╭── D:\stitch-v1.5.0-windows\DETA TEST\hawk.mztab:19809:227
│
19807 │ PSM SYTLLELPPTPSGTTTLSKGNVVT 19746 null null null null "[MS, MS:1003281, Casanovo, 4.1.0]" -0.505144049 null nu …
19808 │ PSM LSADLDELM+15.995DTALREELQNPLEELREEVGTHLDLS 19747 null null null null "[MS, MS:1003281, Casanovo, 4.1.0]" -0 …
19809 │ …=19767 null null null null "0.27434,0.24810,0.24681,0.20568,0.23882,0.23139,0.20678,0.24179,0.22357,0.19806,0.…
· ────────
19810
```

**Comment by wenjinwu1985** [comment]
-Run Info---------------
Version : 1.5
Runname : monoclonal_try_HT-280

Here the input can be defined, this will be used in the TemplateMatching and Recombine steps
Input ->
Casanovo ->
Path : D:\stitch-v1.5.0-windows\DETA TEST\hawk2.mztab
Name : try_casanovo
FilterPPM: 10
CutoffScore: 0.9
FragmentationMethod: All
<-
<-

Template matching matches the reads defined in 'Input' to the given Templates defined in the different groups in the 'Segments'
TemplateMatching ->
EnforceUnique : 0.9
CutoffScore : 10
AmbiguityThreshold : 0.9

include!(../alphabets/mass_alphabet.txt)

Segments->
include!(../templates/Homo_sapiens_Heavy_Chain.txt)
include!(../templates/Homo_sapiens_Light_Chain.txt)
include!(../templates/common_contaminants.txt)
<-
<-

Recombine->
-Pick the highest scoring templates from each segment
N : 1
-Decoy : True
CutoffScore: 10

-Separated by whitespace means directly attached
-Separated by * means with a gap attached
Order->
    Homo sapiens Heavy Chain: IGHV * IGHJ IGHC
    Homo sapiens Light Chain: IGLV IGLJ IGLC
<-
<-

Report ->
Folder: ../results/{datetime} {name}/
HTML ->
Path: report-monoclonal.html
<-
FASTA ->
Path: report-monoclonal-tm.fasta
OutputType: TemplateMatching
<-
CSV ->
Path: report-monoclonal-tm.csv
OutputType: TemplateMatching
<-
FASTA ->
Path: report-monoclonal-rec.fasta
OutputType: Recombine
<-
CSV ->
Path: report-monoclonal-rec.csv
OutputType: Recombine
<-
<-

**Comment by wenjinwu1985** [comment]
[DETA TEST.zip](https://github.com/snijderlab/stitch/files/15131749/DETA.TEST.zip)


Error: Not a valid number
      ╭── H:\MASS\stitch-v1.5.0-windows\DETA TEST\hawk2.mztab:19808:2
      │
19806 │ PSM C+57.021LNDGNTC+57.021VFLFPGKTKVTLLLRPPKN 19745 null null null null "[MS, MS:1003281, Casanovo, 4.1.0]" -0.…
19807 │ PSM C+57.021DDC+57.021KEELLDKEELDKLLLGQPTYVDDTMKK 19746 null null null null "[MS, MS:1003281, Casanovo, 4.1.0]"…
19808 │ PSM C+57.021LLDKDQLNNLLQTYRELLPC+57.021LTQPGHSPC+57.021LLK 19747 null null null null "[MS, MS:1003281, Casanovo…
      · ────────
19809 │
      ╵


Error: Not a valid number
      ╭── H:\MASS\stitch-v1.5.0-windows\DETA TEST\hawk2.mztab:19808:259
      │
19806 │ PSM C+57.021LNDGNTC+57.021VFLFPGKTKVTLLLRPPKN 19745 null null null null "[MS, MS:1003281, Casanovo, 4.1.0]" -0.…
19807 │ PSM C+57.021DDC+57.021KEELLDKEELDKLLLGQPTYVDDTMKK 19746 null null null null "[MS, MS:1003281, Casanovo, 4.1.0]"…
19808 │ …l null null "0.31036,0.28814,0.25934,0.60177,0.53547,0.53506,0.29692,0.52535,0.66003,0.53756,0.48306,0.27533,0…
      ·                                                             ────────
19809 │
      ╵

**Comment by wenjinwu1985** [comment]
"mztab cannot be uploaded because I compressed it."

**Comment by douweschulte** [comment]
The files you added I can open and there does not seem to be a problem at the indicated lines, but these files also do not look like the errors you gave. Did you upload the same files as you ran through stitch?

**Comment by wenjinwu1985** [comment]
-Run Info---------------
Version         : 1.5
Runname         : monoclonal_try_HT-280

- Here the input can be defined, this will be used in the TemplateMatching and Recombine steps
Input ->
    Casanovo ->
        Path     : H:\MASS\stitch-v1.5.0-windows\DETA TEST\hawk2.mztab
        Name     : try_casanovo
        FilterPPM: 10
        CutoffScore: 0.9
        FragmentationMethod: All
    <-
<-

- Template matching matches the reads defined in 'Input' to the given Templates defined in the different groups in the 'Segments'
TemplateMatching ->
    EnforceUnique      : 0.9
    CutoffScore        : 10
    AmbiguityThreshold : 0.9

    include!(../alphabets/mass_alphabet.txt)

    Segments->
        include!(../templates/Mus_musculus_Heavy_Chain.txt)
        include!(../templates/Mus_musculus_Light_Chain.txt)
        include!(../templates/common_contaminants.txt)
    <-
<-

Recombine->
    -Pick the <n> highest scoring templates from each segment
    N          : 1
    -Decoy      : True
    CutoffScore: 10

    -Separated by whitespace means directly attached
    -Separated by * means with a gap attached
    Order->
        MusHeavy: IGHV * IGHJ IGHC
        MusLight: IGLV IGLJ IGLC
    <-
<-

Report ->
    Folder: ../results/{datetime} {name}/
    HTML ->
        Path: report-monoclonal.html
    <-
    FASTA ->
        Path: report-monoclonal-tm.fasta
        OutputType: TemplateMatching
    <-
    CSV ->
        Path: report-monoclonal-tm.csv
        OutputType: TemplateMatching
    <-
    FASTA ->
        Path: report-monoclonal-rec.fasta
        OutputType: Recombine
    <-
    CSV ->
        Path: report-monoclonal-rec.csv
        OutputType: Recombine
    <-
<-

**Comment by wenjinwu1985** [comment]
[1.zip](https://github.com/snijderlab/stitch/files/15132246/1.zip)
[2.zip](https://github.com/snijderlab/stitch/files/15132248/2.zip)
"I have 14 files. I compressed them into two separate archives. These files are for mouse IgG."

**Comment by wenjinwu1985** [comment]
Can we communicate via email?

**Comment by douweschulte** [comment]
Yes we can, but I determined the error. The file you sent contains double quotes around the aa_scores column in the mztab, which Stitch did not expect. There is a fixed version building right now in about an hour you can download that one and see if that fixes your problem.

**Comment by wenjinwu1985** [comment]
I can download the latest version over there, right? Thank you

**Comment by wenjinwu1985** [comment]
"I don't know where to look or how to use it.

**Comment by wenjinwu1985** [comment]
![image](https://github.com/snijderlab/stitch/assets/67898812/b98a941f-bb9a-444d-80ac-615982c3c51c)

**Comment by douweschulte** [comment]
You will have to download the new binary at the GitHub action page: https://github.com/snijderlab/stitch/actions/runs/8850775149. That version wil work the same as the current version, let me know if it does not solve the problem

**Comment by wenjinwu1985** [comment]
ok

**Comment by wenjinwu1985** [comment]
<img width="725" alt="image" src="https://github.com/snijderlab/stitch/assets/67898812/a56b536e-79be-4c16-855a-063e32e8f514">

**Comment by wenjinwu1985** [comment]
<img width="725" alt="image" src="https://github.com/snijderlab/stitch/assets/67898812/afa20b6a-b078-492f-a3f6-b5654f0fd407">

**Comment by wenjinwu1985** [comment]
<img width="725" alt="image" src="https://github.com/snijderlab/stitch/assets/67898812/097d410a-4b2a-4dcf-a2c5-d4590e764040">

**Comment by wenjinwu1985** [comment]
[Peng2021_Herceptin_aspN.zip](https://github.com/snijderlab/stitch/files/15146830/Peng2021_Herceptin_aspN.zip)

**Comment by douweschulte** [comment]
This file seems to be slightly corrupted in the second line. Could you remove the line starting with `casanovo sequence  -o H:` and try again?

**Comment by wenjinwu1985** [comment]
Can you send me the file that you've processed and can run? I'd like to take a look. Thank you

**Comment by douweschulte** [comment]
[Peng2021_Herceptin_aspN_fixed.zip](https://github.com/snijderlab/stitch/files/15146931/Peng2021_Herceptin_aspN_fixed.zip)

**Comment by wenjinwu1985** [comment]
<img width="965" alt="image" src="https://github.com/snijderlab/stitch/assets/67898812/8dc75c55-2242-4f78-8719-9296f4d1cc48">
I deleted the red parts, but it still doesn't work. Can you please translate?

**Comment by douweschulte** [comment]
Deleting that whole line in something like notepad should work. Notepad makes it a bit easier to not leave empty lines and such in the final file.

**Comment by wenjinwu1985** [comment]
<img width="646" alt="image" src="https://github.com/snijderlab/stitch/assets/67898812/24db5fd6-5d12-4acb-a0c9-88f965a6a8f2">
<img width="718" alt="image" src="https://github.com/snijderlab/stitch/assets/67898812/b29122bc-9191-42fb-9d05-91d5d57158d3">

**Comment by douweschulte** [comment]
The whole line has to be deleted. This line is not valid according to the specification of mzTab files.

**Comment by wenjinwu1985** [comment]
<img width="648" alt="8ee39079c82db2f601929086e20107b" src="https://github.com/snijderlab/stitch/assets/67898812/e3dda19a-82cd-45ba-832f-cc0e84f5a12c">
<img width="722" alt="image" src="https://github.com/snijderlab/stitch/assets/67898812/dd737488-ce9d-46b3-9950-1c848f04aa56">

**Comment by wenjinwu1985** [comment]
"Yes, I downloaded the file from the homepage. Is the difficulty on my end? Would it be convenient for you to compress and send me your latest file via email?"

**Comment by douweschulte** [comment]
> [Peng2021_Herceptin_aspN_fixed.zip](https://github.com/snijderlab/stitch/files/15146931/Peng2021_Herceptin_aspN_fixed.zip)

Here is the fixed results file.

**Comment by douweschulte** [comment]
And here is a direct link to the latest Stitch version: https://github.com/snijderlab/stitch/actions/runs/8850775149/artifacts/1451480417

**Comment by wenjinwu1985** [comment]
<img width="541" alt="image" src="https://github.com/snijderlab/stitch/assets/67898812/b542e04a-6fbe-4796-9def-47e694ef23c4">
<img width="562" alt="image" src="https://github.com/snijderlab/stitch/assets/67898812/6b2545f4-450c-4813-bd3a-0e94c275a74f">

**Comment by douweschulte** [comment]
If you run `stitch --version` it should show the following:
![image](https://github.com/snijderlab/stitch/assets/25853274/6ce786f3-3b7b-4f1c-bbda-5e03d30955b6)
If it does you know you have the latest version.

**Comment by wenjinwu1985** [comment]
"Sorry, I don't know how to update the file you provided. I tried using the fixed file you gave me, but it still showed errors. So, it seems the issue is that I haven't updated it. Can you help me with this? Thank you."

**Comment by wenjinwu1985** [comment]
<img width="341" alt="image" src="https://github.com/snijderlab/stitch/assets/67898812/4c8379ec-29a2-4c7d-9ba9-28c1b0678ab4">

**Comment by wenjinwu1985** [comment]
<img width="717" alt="image" src="https://github.com/snijderlab/stitch/assets/67898812/c4c92607-e58e-48f5-8d7b-8f519d17db4b">

"Thank you very much. I have successfully run it. Thank you for your help!"

**Comment by douweschulte** [comment]
You are welcome.

**Comment by wenjinwu1985** [comment]
The content translates to: "I'm currently encountering errors while performing calculations using time data exported from the Denovo software. The errors are as follows. Could you please take a look? Thank you.

<img width="1030" alt="image" src="https://github.com/snijderlab/stitch/assets/67898812/de5a743d-2514-4f42-b97f-77a17d3aa17b">
[Uploading 280 Sample 1denovo - 2.csv…]()

**Comment by douweschulte** [comment]
Could you retry uploading the data file?

**Comment by wenjinwu1985** [comment]
[Uploading 280 Sample 1denovo - 2.csv…]()

**Comment by wenjinwu1985** [comment]
-Run Info---------------
Version         : 1.5
Runname         : monoclonal_try_casanovo

- Here the input can be defined, this will be used in the TemplateMatching and Recombine steps
Input ->
    Casanovo ->
        Path     : H:\MASS\nightly-deploy-windows(1)\DETA1\DETA2\Peng2021_Herceptin_sanmple.mztab
        Name     : try_casanovo
        FilterPPM: 10
        CutoffScore: 0.9
        FragmentationMethod: All
    <-
<-

- Template matching matches the reads defined in 'Input' to the given Templates defined in the different groups in the 'Segments'
TemplateMatching ->
    EnforceUnique      : 0.95
    CutoffScore        : 10
    AmbiguityThreshold : 0.9

    include!(../alphabets/mass_alphabet.txt)

    Segments->
        include!(../templates/Homo_sapiens_Heavy_Chain.txt)
        include!(../templates/Homo_sapiens_Light_Chain.txt)
        include!(../templates/common_contaminants.txt)
    <-
<-

Recombine->
    -Pick the <n> highest scoring templates from each segment
    N          : 1
    -Decoy      : True
    CutoffScore: 10

    -Separated by whitespace means directly attached
    -Separated by * means with a gap attached
    Order->
        Homo sapiens Heavy Chain: IGHV * IGHJ IGHC
        Homo sapiens Light Chain: IGLV IGLJ IGLC
    <-
<-

Report ->
    Folder: ../results/{datetime} {name}/
    HTML ->
        Path: report-monoclonal.html
    <-
    FASTA ->
        Path: report-monoclonal-tm.fasta
        OutputType: TemplateMatching
    <-
    CSV ->
        Path: report-monoclonal-tm.csv
        OutputType: TemplateMatching
    <-
    FASTA ->
        Path: report-monoclonal-rec.fasta
        OutputType: Recombine
    <-
    CSV ->
        Path: report-monoclonal-rec.csv
        OutputType: Recombine
    <-
<-

**Comment by wenjinwu1985** [comment]
"Is there a tutorial available for these settings? I'm not sure which ones can affect accuracy."

As for tutorials, I can't say for certain without more context. You might want to check the documentation or resources provided by the software or platform you're using. Often, they include tutorials or guides that explain each setting and its impact on the analysis process. If there's a specific software or tool associated with these settings, looking up its documentation or searching online for tutorials related to it would be a good starting point. If you provide more details about the software or platform, I can try to provide more targeted guidance or suggestions for finding tutorials.

**Comment by wenjinwu1985** [comment]
[280 Sample 1denovo - 2.csv](https://github.com/snijderlab/stitch/files/15149157/280.Sample.1denovo.-.2.csv)

**Comment by wenjinwu1985** [comment]
Can you share the manual?"

**Comment by douweschulte** [comment]
You can find it in the list of releases. For each release the manual is added as pdf.

**Comment by douweschulte** [comment]
> [280 Sample 1denovo - 2.csv](https://github.com/snijderlab/stitch/files/15149157/280.Sample.1denovo.-.2.csv)

Are you sure you ran this with the correct file format specifications. It looks like a PEAKS file so you will have to specify that and specify the correct file format version otherwise you get errors like the ones above. In the manual are all possible versions listed.

**Comment by wenjinwu1985** [comment]
<img width="617" alt="image" src="https://github.com/snijderlab/stitch/assets/67898812/9e0189d1-6e28-4c01-974b-654e46e17ffe">
Is it this manual?"

**Comment by douweschulte** [comment]
> <img alt="image" width="419" src="https://private-user-images.githubusercontent.com/67898812/326443714-3163e8e4-af36-49f3-842c-6691364f272f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzOTc2MzgsIm5iZiI6MTcxNDM5NzMzOCwicGF0aCI6Ii82Nzg5ODgxMi8zMjY0NDM3MTQtMzE2M2U4ZTQtYWYzNi00OWYzLTg0MmMtNjY5MTM2NGYyNzJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDEzMjg1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmNTE1ZjY5NmYzYjY4NmY0NzJhZmY4ODY4M2M1MGYwZWE3ODA1MjBiOWExOTI1MWRiY2EyNGI2NWYzNmZkOTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rCCD9a13tWfBJ8gCgS5BOwlMZ2QcdMb7CdBFnt4ISpQ"> <img alt="image" width="754" src="https://private-user-images.githubusercontent.com/67898812/326443833-ba1660c5-5462-4036-b4b0-a1305cf33051.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzOTc2MzgsIm5iZiI6MTcxNDM5NzMzOCwicGF0aCI6Ii82Nzg5ODgxMi8zMjY0NDM4MzMtYmExNjYwYzUtNTQ2Mi00MDM2LWI0YjAtYTEzMDVjZjMzMDUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDEzMjg1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjMDU1Nzk4MjJlY2Q2OTBkN2ViNTY4YjliMzg0NDVlMDQyY2RmMDM4NWE1OWU0MWI2ZWVhNzdkYzdmZTJjOGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ES0SX-B-77flOAZX_il_xEDTLo-eSKnfN7dtASpBSUg">

Version eleven means you need to set `11` in stitch.

**Comment by wenjinwu1985** [comment]
> On the peaks version: version eleven means you need to set in stitch.`11`

"I didn't understand what you meant by this sentence."

**Comment by wenjinwu1985** [comment]
<img width="1404" alt="image" src="https://github.com/snijderlab/stitch/assets/67898812/8e673fde-5612-43a1-ab20-06928f9babc5">

**Comment by douweschulte** [comment]
Use:
```
Input ->
    Peaks ->
        Path: ...
        Format: 11
        ....
    <-
<-
```

But know that the files distributed with Stitch are peaks `X+`. 

I find it hard to help you through English. Do you have any colleagues that have a better grasp of English that could help you understanding what you are doing?
